#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# setup_tools.sh — clone + vendor every open-source OSINT & accessibility tool.
#
# Clones each tool's SOURCE repo into third_party/ (provenance + your explicit
# ask to "clone them"), builds the Go recon tools into third_party/bin/, installs
# the Node accessibility engines into the js/ runner dir, and records exact
# resolved commits/versions in third_party/VERSIONS.lock (stamped into reports).
#
# Idempotent. Individual tool failures are logged, not fatal — the pipeline
# degrades honestly (a missing engine => "Needs Manual Review", never a Pass).
#
# Run in WSL2/Ubuntu or the tools Docker image:  bash scripts/setup_tools.sh
# ─────────────────────────────────────────────────────────────────────────────
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TP="$ROOT/third_party"
BIN="$TP/bin"
JS="$ROOT/backend/app/scanners/web/js"
LOCK="$TP/VERSIONS.lock"
mkdir -p "$BIN"
: > "$LOCK"
echo "# Vendored tool versions — generated by setup_tools.sh" >> "$LOCK"
echo "# $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$LOCK"

log()  { printf '\033[1;36m[setup]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[warn ]\033[0m %s\n' "$*"; }

# clone_or_pull <name> <git-url>
clone_or_pull() {
  local name="$1" url="$2" dir="$TP/$name"
  if [ -d "$dir/.git" ]; then
    log "updating $name"; git -C "$dir" pull --ff-only --quiet || warn "pull failed: $name"
  else
    log "cloning $name"; git clone --depth 1 --quiet "$url" "$dir" || { warn "clone failed: $name"; return 1; }
  fi
  local commit; commit="$(git -C "$dir" rev-parse --short HEAD 2>/dev/null || echo '?')"
  echo "$name  commit=$commit  $url" >> "$LOCK"
}

# ── Go recon tools (ProjectDiscovery MIT, OWASP Apache-2.0) ──
build_go() {
  local name="$1" url="$2" pkg="$3"
  clone_or_pull "$name" "$url" || return
  if command -v go >/dev/null 2>&1; then
    log "building $name"
    ( cd "$TP/$name" && go build -o "$BIN/$name" "$pkg" ) \
      && log "built $BIN/$name" || warn "go build failed: $name (will fall back if on PATH)"
  else
    warn "go not found — skipping build of $name"
  fi
}

log "=== OSINT / recon (Go) ==="
build_go subfinder https://github.com/projectdiscovery/subfinder  ./v2/cmd/subfinder
build_go httpx     https://github.com/projectdiscovery/httpx      ./cmd/httpx
build_go katana    https://github.com/projectdiscovery/katana     ./cmd/katana
build_go urlfinder https://github.com/projectdiscovery/urlfinder  ./cmd/urlfinder
# Amass v5 (Apache-2.0) — cloned for provenance; passive-only, optional. Not built
# by default (graph-DB/heavy). Uncomment to build:
clone_or_pull amass https://github.com/owasp-amass/amass || true

# ── Web accessibility engines (cloned for provenance) ──
log "=== accessibility engines (source, provenance) ==="
clone_or_pull axe-core          https://github.com/dequelabs/axe-core        || true
clone_or_pull pa11y             https://github.com/pa11y/pa11y               || true
clone_or_pull HTML_CodeSniffer  https://github.com/squizlabs/HTML_CodeSniffer|| true
clone_or_pull lighthouse        https://github.com/GoogleChrome/lighthouse   || true
clone_or_pull equal-access      https://github.com/IBMa/equal-access         || true

# ── Mobile (cloned now, wired in Phases 4–5) ──
log "=== mobile (source, provenance) ==="
clone_or_pull atf-android https://github.com/google/Accessibility-Test-Framework-for-Android || true
clone_or_pull appium      https://github.com/appium/appium || true

# ── Node engines: install the runnable published packages in the js/ runner ──
log "=== installing Node engine runners ($JS) ==="
if command -v npm >/dev/null 2>&1; then
  ( cd "$JS" && npm install --no-audit --no-fund ) && {
    log "npm install OK; recording versions"
    ( cd "$JS" && npm ls --depth=0 2>/dev/null | sed 's/^/  /' >> "$LOCK" ) || true
    log "installing Playwright Chromium"
    if [ "${1:-}" = "--docker" ]; then
      ( cd "$JS" && npx --yes playwright install chromium ) || warn "playwright install failed"
    else
      ( cd "$JS" && npx --yes playwright install --with-deps chromium ) || warn "playwright install failed"
    fi
  } || warn "npm install failed in $JS"
else
  warn "npm not found — Node engines will report engine errors (fail-closed)."
fi

log "Done. Versions recorded in $LOCK"
echo
cat "$LOCK"
